spring:
  application:
    name: dbshield-backup-orchestrator-service

  profiles:
    active: local

  kafka:

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 2147483647
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 120000
        request.timeout.ms: 30000
        max.in.flight.requests.per.connection: 5

    consumer:
      group-id: backup-orchestrator
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: db.shield.backup.orchestrator.service.dto.event.BackupRequestedEvent

    listener:
      ack-mode: record
      concurrency: 6
      no-poll-threshold: 300000